name: nostr_address_book
description: Local-first Nostr address book backed by vCard 4.0 events.
version: 0.1.0
repository: https://github.com/nogringo/nostr-address-book

topics:
  - nostr
  - address-book
  - vcard
  - offline-first

environment:
  sdk: ^3.12.1

dependencies:
  broadcast_queue_shim_for_ndk: ^0.2.1
  ndk: ^0.8.4-dev.5
  sembast: ^3.8.8+1
  uuid: ^4.5.3
  vcard_dart: ^2.1.0

dev_dependencies:
  bip340: ^0.3.1
  lints: ^6.0.0
  test: ^1.25.6
